/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BodyComponent: typeof import('./src/components/BodyComponent.vue')['default']
    CardWhite: typeof import('./src/components/cards/CardWhite.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    FormInput: typeof import('./src/components/form/FormInput.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Lightbutton: typeof import('./src/components/buttons/Lightbutton.vue')['default']
    LoginCard: typeof import('./src/components/login/LoginCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestButton: typeof import('./src/components/TestButton.vue')['default']
  }
}
